### ISSUE TITLE
能否去除对Rxjava的依赖

### ISSUE THREAD

**Issue by hujiaweibujidao** [Yasic/QQBubbleView#1]
你好，这个动画的效果很不错。

我有个小建议，我看源码对于Rxjava的依赖并不大，可否考虑去除对Rxjava的依赖呢？

**Comment by Yasic** [comment]
非常感谢您的建议、主要是近期一直在熟悉Rx的东西，所以顺手把两个依赖都加入了
刚刚已去除依赖并push一次
